config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :blogs do
   resources :comments

   collection do
     post :confirm
   end
  end

 resource :contacts, only: [:new, :create] do

  collection do
   post :confirm
  end
 end

 resources :conversations do
  resources :messages
 end

root :to =>'top#index'

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

resources :poems, only: [:index, :show]

devise_for :users, controllers: {
 registrations: "users/registrations",
 omniauth_callbacks: "users/omniauth_callbacks"
}

resources :users, only: [:index, :show]

 resources :relationships, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog

  has_many :notifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @blog = @comment.blog
    @notification = @comment.notifications.build(user_id: @blog.user.id )
    # クライアント要求に応じてフォーマットを変更
     respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_path(@blog), notice: 'コメントを投稿しました。' }
        unless @comment.blog.user_id == current_user.id
          Pusher.trigger("user_#{@comment.blog.user_id}_channel", 'comment_created', {
            message: 'あなたの作成したブログにコメントが付きました'
          })
        end
        Pusher.trigger("user_#{@comment.blog.user_id}_channel", 'notification_created', {
          unread_counts: Notification.where(user_id: @comment.blog.user.id, read: false).count
        })
        format.js { render :index }
        flash[:notice]  = '作成しました！'
      else
        format.html { render :new }
      end
    end
  end

   def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to blog_path(@blog), notice: 'コメントを削除しました。' }
      format.js { render :index }
    end
  end

  def edit
     @comment=Comment.find(params[:id])
     @blog = @comment.blog
   end

  def update
     @comment=Comment.find(params[:id])
     if @comment.update(comment_params)
       redirect_to blog_path(@comment.blog), notice: "コメントを更新しました"
     else
       render 'edit'
     end
  end



 private

   def comment_params
     params.require(:comment).permit(:blog_id, :content)
   end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([blog, comment], remote: true) do |f| %>
  <%= f.hidden_field :blog_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<%= notice %>

<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
           <%= link_to '', edit_blog_comment_path(blog, comment), class: "fa fa-pencil-square-o fa-lg" %>
          <%= link_to '', blog_comment_path(blog, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<h2>編集画面</h2>
<div class="container">
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
      <% if @comment.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <ul>
            <% @comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= render partial: 'form', locals: { comment: @comment, blog: @blog } %>
  </div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$(':text').val('')